version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build_android:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.16.4
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - ruby/install-deps
workflows:
  version: 2
  build:
    jobs:
      - build_android:
          filters:
            branches:
              only: master
