# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :upload_firebase do
    release = firebase_app_distribution(
            app: "1:1084114691839:android:5e64f2a9f45fa69cc98eca",
            android_artifact_path: 'build/app/outputs/apk/release/app-release.apk',
            service_credentials_file: "android/app/firebase_login_credentials.json",
            testers: "mig.ruiz@gmail.com,soniacarolina.blanco@gmail.com",
            release_notes: changelog_from_git_commits(
              commits_count: "5",
              merge_commit_filtering: "exclude_merges"
            )
        )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


end
